// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdaY5nIvXYoL6tfywJUVx0yc3XBcOiSRc',
    appId: '1:478195767837:web:9333209689ba856df1c4f4',
    messagingSenderId: '478195767837',
    projectId: 'hiddentreausers',
    authDomain: 'hiddentreausers.firebaseapp.com',
    storageBucket: 'hiddentreausers.firebasestorage.app',
    measurementId: 'G-XZZ9EZ2QK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaAzljG1mDFJnF6-T7PGe8niWks0r7r6A',
    appId: '1:478195767837:android:d433a4bb2efbbe5cf1c4f4',
    messagingSenderId: '478195767837',
    projectId: 'hiddentreausers',
    storageBucket: 'hiddentreausers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7kFoUWPnpd7ACMnAxodX1J4LKqtnWkt4',
    appId: '1:478195767837:ios:990f111833e7cdd6f1c4f4',
    messagingSenderId: '478195767837',
    projectId: 'hiddentreausers',
    storageBucket: 'hiddentreausers.firebasestorage.app',
    iosBundleId: 'com.example.hiddenTreasures',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7kFoUWPnpd7ACMnAxodX1J4LKqtnWkt4',
    appId: '1:478195767837:ios:990f111833e7cdd6f1c4f4',
    messagingSenderId: '478195767837',
    projectId: 'hiddentreausers',
    storageBucket: 'hiddentreausers.firebasestorage.app',
    iosBundleId: 'com.example.hiddenTreasures',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdaY5nIvXYoL6tfywJUVx0yc3XBcOiSRc',
    appId: '1:478195767837:web:bfd71791634e70e6f1c4f4',
    messagingSenderId: '478195767837',
    projectId: 'hiddentreausers',
    authDomain: 'hiddentreausers.firebaseapp.com',
    storageBucket: 'hiddentreausers.firebasestorage.app',
    measurementId: 'G-3XY6V1BJTC',
  );
}
